import os
import sys

# Ensure backend folder is in PYTHONPATH
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from backend.crawler import WebCrawler
from backend.parsers import UnifiedParser
from backend.chunker import SmartChunker
from backend.vector_store import HybridStore
from backend.llm import LLMManager

def run_integration_test():
    print("==========================================")
    print("      MONIRAG BACKEND PIPELINE TEST       ")
    print("==========================================")

    # 1. Test Crawler on https://example.com
    print("\n[Step 1] Testing Web Crawler on https://example.com...")
    try:
        crawler = WebCrawler("https://example.com", max_depth=0)
        crawled_pages = crawler.crawl()
        print(f"[+] Successfully crawled {len(crawled_pages)} pages.")
        if crawled_pages:
            print(f"    Title: {crawled_pages[0]['title']}")
            print(f"    Chunks extracted: {len(crawled_pages[0]['chunks'])}")
        else:
            print("    [!] Warning: No pages crawled from Example.com.")
            return False
    except Exception as e:
        print(f"[-] Web Crawler test failed: {e}")
        return False

    # 2. Test Parser & Chunker with Mock Text Document
    print("\n[Step 2] Testing Parser & Smart Chunker...")
    mock_file_path = "mock_test_doc.txt"
    try:
        # Write dummy text
        with open(mock_file_path, "w", encoding="utf-8") as f:
            f.write("MoniRAG is an enterprise-grade multi-modal retrieval-augmented generation engine.\n"
                    "It supports 14 different file types, including DOCX, EML, SQLite, Video, and Audio.\n"
                    "The system incorporates reciprocal rank fusion to blend BM25 search with vector similarity scores.\n"
                    "Ollama serves as the primary local LLM, and Groq functions as the cloud fallback LLM.")
        
        # Parse it
        parser = UnifiedParser()
        parsed_doc = parser.parse_file(mock_file_path)
        print(f"[+] Parsed file: {parsed_doc['source']}")
        print(f"    Source Type: {parsed_doc['source_type']}")
        
        # Chunk it
        chunker = SmartChunker(target_chunk_size=150, overlap_size=10)
        chunks = chunker.chunk_document(parsed_doc)
        print(f"[+] Smart Chunker generated {len(chunks)} chunks:")
        for idx, chunk in enumerate(chunks):
            print(f"    Chunk {idx+1}: '{chunk['text']}'")
            
        if not chunks:
            print("    [-] Error: No chunks generated.")
            return False
    except Exception as e:
        print(f"[-] Parser/Chunker test failed: {e}")
        return False
    finally:
        # Clean up mock file
        if os.path.exists(mock_file_path):
            os.remove(mock_file_path)

    # 3. Test Hybrid Store Indexing and Search
    print("\n[Step 3] Testing Hybrid Vector + BM25 Database Store...")
    try:
        # Create store
        test_store_dir = "data/test_store"
        store = HybridStore(persist_dir=test_store_dir)
        store.clear()  # Start clean
        
        # Ingest parsed document chunks
        doc_data = {
            "source_type": parsed_doc["source_type"],
            "source": parsed_doc["source"],
            "chunks": chunks
        }
        store.add_document(doc_data)
        print(f"[+] Added mock document. Total index size: {len(store.chunks)} chunks.")
        
        # Test Search
        query = "How many file types does MoniRAG support?"
        print(f"[*] Querying database: '{query}'")
        search_results = store.search(query, top_k=2, mode="hybrid")
        print(f"[+] Search yielded {len(search_results)} results:")
        for res in search_results:
            print(f"    - Rank {res['rank']} ({res['metadata']['source']}): '{res['text']}'")
            print(f"      (RRF Rank Score: {res['rrf_score']:.4f} | Vector Sim: {res['vector_score']:.4f} | BM25: {res['bm25_score']:.4f})")
            
        if not search_results:
            print("    [-] Error: Search returned no results.")
            return False
    except Exception as e:
        print(f"[-] Hybrid Store test failed: {e}")
        return False

    # 4. Test LLM Answer Generation
    print("\n[Step 4] Testing LLM Generation Engine...")
    try:
        llm = LLMManager(ollama_model="mistral:latest")
        print("[*] Running answer generation using retrieved context...")
        answer, provider, latency = llm.generate_answer(query, search_results)
        print(f"[+] Answer: '{answer}'")
        print(f"    Generated by: {provider} in {latency}ms")
    except Exception as e:
        print(f"[-] LLM generation test failed: {e}")
        # Don't fail the whole test if Ollama is just offline since it could fallback to Groq (which requires an API key)
        print("    (Ollama model might not be running or needs to be downloaded).")

    # Clean up test database files
    try:
        store.clear()
        if os.path.exists(test_store_dir):
            os.rmdir(test_store_dir)
    except Exception:
        pass

    print("\n==========================================")
    print("      INTEGRATION TEST PASSED SUCCESS     ")
    print("==========================================")
    return True

if __name__ == "__main__":
    success = run_integration_test()
    sys.exit(0 if success else 1)
